version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    platform: linux/arm64
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
      - sortsense_db:/app/data
    devices:
      - /dev/video0:/dev/video0
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    platform: linux/arm64
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sortsense_db:
